name : Terraform - deploy Service Bus to env01

trigger: none

variables:
  - group: Terraform_SPN
  - name: rootFolder
    value: './'
  - name: tfvarsFile
    value: 'tfdemo.env01.tfvars'
  - name: adoEnvironment
    value: 'env01'

stages:
- template: ./terraform-template.yml
  parameters:
    rootFolder: $(rootFolder)
    tfvarsFile: $(tfvarsFile)
    adoEnvironment: $(adoEnvironment)